Scalar Broadcasting

In [2]:
import numpy as np

array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [3]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([10, 20, 30])

print(arr1 + arr2)

[[11 22 33]
 [14 25 36]]


Column Broadcasting

In [5]:
arr1 = np.array([[2],
                [4],
                [6]])
arr2 = np.array([10,20,30])

print(arr1 + arr2)

[[12 22 32]
 [14 24 34]
 [16 26 36]]


In [8]:
nolist1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
nolist2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(nolist1.shape)
print(nolist2.shape)



(1, 10)
(10, 1)


In [9]:
print(nolist1 * nolist2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [10]:
print(nolist1 + nolist2)

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [11]:
print(nolist1 - nolist2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [-1  0  1  2  3  4  5  6  7  8]
 [-2 -1  0  1  2  3  4  5  6  7]
 [-3 -2 -1  0  1  2  3  4  5  6]
 [-4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-6 -5 -4 -3 -2 -1  0  1  2  3]
 [-7 -6 -5 -4 -3 -2 -1  0  1  2]
 [-8 -7 -6 -5 -4 -3 -2 -1  0  1]
 [-9 -8 -7 -6 -5 -4 -3 -2 -1  0]]


Aggregate functions

In [12]:
array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print(np.sum(array))

55


In [13]:
print(np.mean(array))

5.5


In [14]:
print(np.std(array))

2.8722813232690143


In [15]:
print(np.var(array))

8.25


In [16]:
print(np.min(array))

1


In [17]:
print(np.max(array))

10


In [18]:
print(np.argmin(array))

0


In [19]:
print(np.argmax(array))

9


In [22]:
print(np.sum(array, axis=0))

[ 7  9 11 13 15]


In [24]:
print(np.sum(array, axis=1))

[15 40]


Filtering

In [29]:
ages = np.array([[23,19,34,21,34,54,32],
               [32,44,66,43,21,44,55]])
teenager = ages[ages < 20]
print(teenager)

[19]


In [30]:
adults =ages[ages >=20]
print(adults)

[23 34 21 34 54 32 32 44 66 43 21 44 55]


In [31]:
adults =ages[(ages >=20) & (ages < 40)]
print(adults)

[23 34 21 34 32 32 21]


In [34]:
#np.where(condition, value_if_true, value_if_false)

adults = np.where (ages >= 20, ages,0)
print(adults)

[[23  0 34 21 34 54 32]
 [32 44 66 43 21 44 55]]


RANDOM NUMBERS


In [38]:
rng = np.random.default_rng()
print(rng.integers(low=1, high=101))

61


In [39]:
print(rng.integers(low=1, high=101, size=6))

[33 42 44 21 74 49]


In [40]:
#2D
print(rng.integers(low=1, high=101, size=(3,2)))

[[56 85]
 [71 20]
 [86 14]]


In [41]:
rng = np.random.default_rng(seed=1)
#2D
print(rng.integers(low=1, high=101, size=(3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [49]:
np.random.seed(seed=1)
print(np.random.uniform(low=-1,high=1,size=(3,2)))


[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [50]:
array = np.array([1,2,3,4,5])
np.random.shuffle(array)
print(array)

[3 1 2 4 5]
